/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;


//import static views.ListPanel.getRandomJPanel;

import java.awt.*;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.*;

import controllers.AdminCatalogueController;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Product;
import network.PackageNotReceivedException;
import network.PackageNotSentException;
import session.Session;


/**
 *
 * @author angel
 */
public class AdminCatalogueView extends javax.swing.JFrame {
    private final AdminCatalogueController controller;

    /**
     * Creates new form Songs
     */
    public AdminCatalogueView() {
        initComponents();
        final ListPanel listPanel = new ListPanel();
        controller = new AdminCatalogueController();

        try {
            List<Product> songs = controller.getSongs();
            songs.forEach(song -> {
                SongInAdminCatalogue sv = new SongInAdminCatalogue(song, new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) { updateActionPerformed(evt, song); }
                }, new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        deleteActionPerformed(evt, song);
                    }
                });
                JPanel panel = sv.getPanel();
                sv.setBackground(new Color(new Random().nextFloat(), new Random().nextFloat(), new Random().nextFloat()));
                listPanel.addPanel(panel);
            });
            this.scrollPanel.setViewportView(listPanel);
            loadingField.setText("");
            userLabel.setText("User: " + Session.getInstance().getUser().get().getUsername());
        } catch (IOException e) {
            throw new RuntimeException(e);
        } catch (PackageNotSentException e) {
            throw new RuntimeException(e);
        } catch (PackageNotReceivedException e) {
            throw new RuntimeException(e);
        }
    }

    private void deleteActionPerformed(java.awt.event.ActionEvent evt, Product song) {
        System.out.println("Clicked");
        try {
            // TOOD show the confirmation message
            //JOptionPane.showConfirmDialog(this, song);
            String response = controller.delteProduct(song);
            JOptionPane.showMessageDialog(this, response);
        } catch (IOException ex) {
            //TOOD show error
            Logger.getLogger(AdminCatalogueView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (PackageNotSentException ex) {
            //TOOD show error
            Logger.getLogger(AdminCatalogueView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (PackageNotReceivedException ex) {
            //TOOD show error
            Logger.getLogger(AdminCatalogueView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void updateActionPerformed(java.awt.event.ActionEvent evt, Product song) {
        dispose();
        new UpdateProductView(song).setVisible(true);
        //TODO another view
    }


    private void logoutButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        Session.getInstance().clearSession();
        Login loginView = new Login();
        loginView.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        scrollPanel = new javax.swing.JScrollPane();
        userLabel = new javax.swing.JLabel();
        loadingField = new javax.swing.JLabel();
        createProductButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Songs");

        logoutButton.setText("Logout");

        userLabel.setText("User:");

        loadingField.setText("Loading...");

        createProductButton.setText("Create");
        createProductButton.setActionCommand("Create");
        createProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProductButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPanel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loadingField)
                            .addComponent(userLabel))
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(createProductButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logoutButton)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logoutButton)
                            .addComponent(jLabel1)
                            .addComponent(createProductButton)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loadingField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProductButtonActionPerformed
        dispose();
        new CreateProductView().setVisible(true);
    }//GEN-LAST:event_createProductButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminCatalogueView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminCatalogueView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminCatalogueView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminCatalogueView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminCatalogueView().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createProductButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loadingField;
    private javax.swing.JButton logoutButton;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
