/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.CartController;
import model.LineItem;
import model.ShippingCart;
import network.PackageNotReceivedException;
import network.PackageNotSentException;
import session.Session;

import javax.swing.*;
import java.io.IOException;

/**
 *
 * @author angel
 */
public class CartView extends javax.swing.JFrame {
    private final CartController cartController;
    private final ListPanel listPanel;
    private final ShippingCart cart;
    /**
     * Creates new form CartView
     */
    public CartView() {
        initComponents();
        cartController = new CartController();

        errorLabel.setText("");
        loadingLabel.setVisible(true);

        cart = cartController.getCart();
        listPanel = new ListPanel();

        cart.getLineItems().forEach(song -> {
            SongInCartView songInCartView = new SongInCartView(song.getProduct(),
                new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        removeProductActionPerformed(evt, song);
                    }
                }
            );
            listPanel.addPanel(songInCartView.getPanel());
        });
        jScrollPane1.setViewportView(listPanel);
        loadingLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        emptyButton = new javax.swing.JButton();
        buyButton = new javax.swing.JButton();
        loadingLabel = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        catalogueButton = new javax.swing.JButton();
        transactionsButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jScrollPane1.setViewportView(jButton1);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Your cart");

        emptyButton.setText("Empty cart");
        emptyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emptyButtonActionPerformed(evt);
            }
        });

        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });

        buyButton.setText("Buy");

        loadingLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        loadingLabel.setText("Loading...");

        errorLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(204, 0, 204));
        errorLabel.setText("jLabel3");

        catalogueButton.setText("Catalogue");
        catalogueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogueButtonActionPerformed(evt);
            }
        });

        transactionsButton.setText("Transactions");

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        transactionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionsButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(loadingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emptyButton)
                        .addGap(26, 26, 26)
                        .addComponent(buyButton)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(catalogueButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transactionsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutButton)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(catalogueButton)
                    .addComponent(transactionsButton)
                    .addComponent(logoutButton))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emptyButton)
                    .addComponent(buyButton)
                    .addComponent(loadingLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLabel)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emptyButtonActionPerformed(java.awt.event.ActionEvent evt) {
        cartController.emptyCart();
        JOptionPane.showMessageDialog(emptyButton, "The cart now is empty");
//     Go to catalogue page
        catalogueButtonActionPerformed(evt);
    }

    private void removeProductActionPerformed(java.awt.event.ActionEvent evt, LineItem song) {
        int selected = JOptionPane.showConfirmDialog(jScrollPane1, "Are you sure to remove "+ song.getProduct().getName() +"?");
        if(selected != JOptionPane.YES_OPTION) return;

        cartController.removeItem(song.getProduct());
        listPanel.removePanel(cart.getLineItems().indexOf(song));
    }

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            errorLabel.setText("");
            int selected = JOptionPane.showConfirmDialog(jScrollPane1, "Are you sure?");
            if(selected != JOptionPane.YES_OPTION) return;

            loadingLabel.setVisible(true);
            cartController.confirmTransaction();
            loadingLabel.setVisible(false);

            JOptionPane.showMessageDialog(buyButton, "Transaction complete");

//            dispose();
//            TransactionsView transactionsView = new TransactionsView();
//            transactionsView.setVisible(true);
        } catch (PackageNotSentException e) {
            errorLabel.setText("Error while connecting with the server");
        } catch (PackageNotReceivedException e) {
            errorLabel.setText("Error while connecting with the server");
        } catch (IOException e) {
            errorLabel.setText("Internal error");
        }
    }

    private void catalogueButtonActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        SongsView songsView = new SongsView();
        songsView.setVisible(true);
    }//GEN-LAST:event_catalogueButtonActionPerformed

    private void transactionsButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        TransactionsView transactionsView = new TransactionsView();
        transactionsView.setVisible(true);
    }

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        dispose();
        Session.getInstance().clearSession();
        Login loginView = new Login();
        loginView.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CartView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyButton;
    private javax.swing.JButton catalogueButton;
    private javax.swing.JButton emptyButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loadingLabel;
    private javax.swing.JButton logoutButton;
    private java.awt.Panel panel1;
    private javax.swing.JButton transactionsButton;
    // End of variables declaration//GEN-END:variables
}
